export const themes = [
    {
        name: 'Default Blue',
        colors: {
            '--color-primary': '#3B82F6',
            '--color-primary-dark': '#2563EB',
            '--color-primary-light': '#EFF6FF',
            '--color-secondary': '#F97316',
            '--color-background': '#F9FAFB',
            '--color-surface': '#FFFFFF',
            '--color-text-dark': '#1F2937',
            '--color-text-medium': '#4B5563',
            '--color-text-light': '#9CA3AF',
            '--color-border': '#E5E7EB',
            '--color-success': '#10B981',
            '--color-danger': '#EF4444',
            '--color-warning': '#F59E0B',
        }
    },
    {
        name: 'Forest Green',
        colors: {
            '--color-primary': '#166534',
            '--color-primary-dark': '#14532D',
            '--color-primary-light': '#F0FDF4',
            '--color-secondary': '#CA8A04',
            '--color-background': '#F9FAFB',
            '--color-surface': '#FFFFFF',
            '--color-text-dark': '#1F2937',
            '--color-text-medium': '#4B5563',
            '--color-text-light': '#9CA3AF',
            '--color-border': '#E5E7EB',
            '--color-success': '#10B981',
            '--color-danger': '#EF4444',
            '--color-warning': '#F59E0B',
        }
    },
    {
        name: 'Sunset Orange',
        colors: {
            '--color-primary': '#EA580C',
            '--color-primary-dark': '#C2410C',
            '--color-primary-light': '#FFF7ED',
            '--color-secondary': '#0891B2',
            '--color-background': '#F9FAFB',
            '--color-surface': '#FFFFFF',
            '--color-text-dark': '#1F2937',
            '--color-text-medium': '#4B5563',
            '--color-text-light': '#9CA3AF',
            '--color-border': '#E5E7EB',
            '--color-success': '#10B981',
            '--color-danger': '#EF4444',
            '--color-warning': '#F59E0B',
        }
    },
    {
        name: 'Royal Purple',
        colors: {
            '--color-primary': '#7E22CE',
            '--color-primary-dark': '#6B21A8',
            '--color-primary-light': '#F5F3FF',
            '--color-secondary': '#DB2777',
            '--color-background': '#F9FAFB',
            '--color-surface': '#FFFFFF',
            '--color-text-dark': '#1F2937',
            '--color-text-medium': '#4B5563',
            '--color-text-light': '#9CA3AF',
            '--color-border': '#E5E7EB',
            '--color-success': '#10B981',
            '--color-danger': '#EF4444',
            '--color-warning': '#F59E0B',
        }
    },
    {
        name: 'Graphite Gray',
        colors: {
            '--color-primary': '#4B5563',
            '--color-primary-dark': '#374151',
            '--color-primary-light': '#F3F4F6',
            '--color-secondary': '#3B82F6',
            '--color-background': '#F9FAFB',
            '--color-surface': '#FFFFFF',
            '--color-text-dark': '#1F2937',
            '--color-text-medium': '#4B5563',
            '--color-text-light': '#9CA3AF',
            '--color-border': '#E5E7EB',
            '--color-success': '#10B981',
            '--color-danger': '#EF4444',
            '--color-warning': '#F59E0B',
        }
    },
    {
        name: 'Oceanic Teal',
        colors: {
            '--color-primary': '#0D9488',
            '--color-primary-dark': '#0F766E',
            '--color-primary-light': '#F0FDFA',
            '--color-secondary': '#0EA5E9',
            '--color-background': '#F8FAFC',
            '--color-surface': '#FFFFFF',
            '--color-text-dark': '#1E293B',
            '--color-text-medium': '#475569',
            '--color-text-light': '#94A3B8',
            '--color-border': '#E2E8F0',
            '--color-success': '#22C55E',
            '--color-danger': '#F43F5E',
            '--color-warning': '#F59E0B',
        }
    },
    {
        name: 'Ruby Red',
        colors: {
            '--color-primary': '#BE123C',
            '--color-primary-dark': '#9F1239',
            '--color-primary-light': '#FFF1F2',
            '--color-secondary': '#F59E0B',
            '--color-background': '#F8FAFC',
            '--color-surface': '#FFFFFF',
            '--color-text-dark': '#1E293B',
            '--color-text-medium': '#475569',
            '--color-text-light': '#94A3B8',
            '--color-border': '#E2E8F0',
            '--color-success': '#22C55E',
            '--color-danger': '#F43F5E',
            '--color-warning': '#F59E0B',
        }
    },
    {
        name: 'Sakura Pink',
        colors: {
            '--color-primary': '#EC4899',
            '--color-primary-dark': '#DB2777',
            '--color-primary-light': '#FDF2F8',
            '--color-secondary': '#A78BFA',
            '--color-background': '#F8FAFC',
            '--color-surface': '#FFFFFF',
            '--color-text-dark': '#1E293B',
            '--color-text-medium': '#475569',
            '--color-text-light': '#94A3B8',
            '--color-border': '#E2E8F0',
            '--color-success': '#22C55E',
            '--color-danger': '#F43F5E',
            '--color-warning': '#F59E0B',
        }
    }
];
